### PR TITLE
0.13 Update & Extra Options

### LINKED ISSUE #6: The argument "user" was already set at main.tf:104,3-7. Each argument may be set only once.
Error: Attribute redefined

  on main.tf line 111, in resource "aws_mq_broker" "default":
 111:   user = [{

The argument "user" was already set at main.tf:104,3-7. Each argument may be
set only once.

### PR DESCRIPTION
**Pull request by Makeshift**
* Update to TF 0.13 syntax
* Make adding secrets to SSM optional
* User can provide a KMS key or we can create one for them (if they opt to store secrets in SSM)
* Skip resources if we don't need them
* Also fixes #6

### CODE REVIEW

**Comment by Gowiem** [comment]
@Makeshift looks like this effort was largely tackled by #12. Want to rebase and make your edits against the latest?

**Comment by Gowiem** [comment]
@Makeshift ping.

**Comment by Gowiem** [comment]
@Makeshift friendly ping.

**Comment by Nuru** [comment]
Closing this PR as abandoned and out-of-date. If anyone wants to revisit any of these changes, please open a new PR.

**Pull request closed without merging**
