### PR TITLE
Ignore changes to `engine_version` once set

### PR DESCRIPTION
**Pull request by nitrocode**
## what
* Ignore changes to `engine_version` once set

## why
* If this isn't added and `auto_minor_version_upgrade` is enabled, then each plan will try to downgrade the version back to an older version. This can be destructive if `apply_immediately` is also enabled.

## references
N/A

### CODE REVIEW

**Comment by nitrocode** [comment]
This is blocked by the sg module refactor https://github.com/cloudposse/terraform-aws-security-group/pull/17

**Review by Gowiem — APPROVED** [review]

**Review by Gowiem — APPROVED** [review]

**Comment by Gowiem** [comment]
@nitrocode this looks solid to me. Merge whenever you're ready.

**Comment by Nuru** [comment]
I am vetoing this PR for the following reasons:

- Because of [Terraform limitations](https://www.terraform.io/language/meta-arguments/lifecycle#literal-values-only), there is no way to configure an option for `engine_version` to be ignored or not ignored.
-  If this PR were applied and changes to `engine_version` were therefore ignored, there would be no way to upgrade the engine version via Terraform.

After an auto-upgrade happens, the IaC configuration needs to be updated to match. This is part of the "contract" of Infrastructure as Code: the code reflects the desired state of the infrastructure. Strict adherence to this contract would forbid the use of the auto-upgrade feature and require a process to update the version in the code and apply the update. Allowing the update to go forward and then back-filling the code is a reasonable alternative.

**Comment by nitrocode** [comment]
Couldn't we do what we did for ecs container module where we have 2 resources, one that ignores the version and the other that doesnt?

@Nuru

**Comment by nitrocode** [comment]
@Nuru just to add to @gberenice said

From PR https://github.com/cloudposse/terraform-aws-rds-cluster/pull/115

> There is a note on the [rds_cluster_instance#engine_version](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster_instance#engine_version) which states
> > (Optional, Forces new resource) The database engine version. When managing the engine version in the cluster, it is recommended to add the [lifecycle ignore_changes configuration](https://www.terraform.io/docs/configuration/meta-arguments/lifecycle.html#ignore_changes) for this argument to prevent Terraform from proposing changes to the instance engine version directly.

**Comment by Nuru** [comment]
@nitrocode 
> @Nuru just to add to @gberenice said
> 
> From PR [cloudposse/terraform-aws-rds-cluster#115](https://github.com/cloudposse/terraform-aws-rds-cluster/pull/115)
> 
> > There is a note on the [rds_cluster_instance#engine_version](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster_instance#engine_version) which states
> > > (Optional, Forces new resource) The database engine version. When managing the engine version in the cluster, it is recommended to add the [lifecycle ignore_changes configuration](https://www.terraform.io/docs/configuration/meta-arguments/lifecycle.html#ignore_changes) for this argument to prevent Terraform from proposing changes to the instance engine version directly.

That comment is out of date, if it was ever accurate. The current AWS provider version is 4.18.0, and its documentation and all the documentation I checked going back as far as version [2.33.0](https://registry.terraform.io/providers/hashicorp/aws/2.33.0/docs/resources/rds_cluster_instance#engine_version) makes no mention of updating the engine forcing a new resource and no recommendation to ignore the engine version. In general, updating the RDS Engine version happens during the maintenance window and is not a problem. For RDS, you are not even required to specify a version, so if you want to ignore it, you can just not specify it to begin with. I consider https://github.com/cloudposse/terraform-aws-rds-cluster/pull/115 to be a mistake.

> 
> The same can be said for mq broker, msk, and other resources that control the engine version and allow auto updating.

Yes. None of them should be ignoring the engine version. 

@gberenice wrote
>@Nuru I wonder if that should be the default behaviour for all the similar scenarios. For example, I see that engine_version is already ignored in terraform-aws-rds-cluster for cluster instance resource (plus there is a draft PR from @nitrocode to complete this feature).

Yes, none of our modules should be ignoring the engine version for the reasons outlined. 

Thanks to community contributions, we have one module (I don't recall which one) which has at least 4 separate copies of the target resource, to handle the combination of `create_before_destroy` and ignoring some element. It is difficult to maintain, but at least with `create_before_destroy` there is a solid argument for using and not using that feature for some kinds of resources. I do not think it is worth the effort to maintain 2 separate copies of the resource to support optionally ignoring the engine version, but even if it were worth the effort, that is not what this PR proposed. This PR proposed forcing the "ignore engine version" option on everyone, which is an unexpected reduction in control not suitable for a minor version PR.

**Pull request closed without merging**
