### PR TITLE
remove deprecated overwrite_ssm_parameter

### PR DESCRIPTION
**Pull request by andruccho**
Removed deprecated `overwrite_ssm_parameter`.

### CODE REVIEW

**Comment by hans-d** [comment]
@andruccho Hi, can you update the pr so that it passes the tests? otherwise, it is likely to be closed due to staleness.

**Comment by andruccho** [comment]
@hans-d Fixed readme which broke the test
This workflow is awaiting approval from a maintainer

**Comment by hans-d** [comment]
I need to look into the terratest check failures, as the failures of those are unrelated to your change.

**Comment by hans-d** [comment]
awaiting #73

**Review by hans-d — APPROVED** [review]

**Comment by hans-d** [comment]
@andruccho merged, and thanks !

**Pull request merged**
